bot.name=flat_444_bot
bot.token=${BOT_TOKEN}

spring.datasource.url=jdbc:postgresql://localhost:5433/app_db
spring.datasource.username=app_user
spring.datasource.password=secretpass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=true
spring.liquibase.change-log=changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
